language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - yarn install --pure-lockfile

script:
  - yarn docs:build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  repo: EasyHexo/easyhexo.com
  target-branch: master
  on:
    branch: master
