language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - yarn install --pure-lockfile

script:
  - npm run docs:build

branches:
  only:
    - dev

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_J
  local_dir: docs/.vuepress/dist
  name: $GIT_NAME_J
  email: $GIT_EMAIL_J
  keep-history: true
  repo: EasyHexo/dev.easyhexo.com
  target-branch: master
  on:
    branch: dev
